const sendOrderSelectQuery = `
      SELECT
        prescription.prescriptionno,
        prescription.seq,
        prescription.seqmax,
        prescription.itemindex,
        COALESCE(packagemaster.orderitembarcode, prescription.orderitembarcode) AS orderitembarcode,
        prescription.patientname,
        prescription.sex,
        prescription.patientdob,
        prescription.hn,
        prescription.an,
        prescription.wardcode,
        prescription.wardname,
        prescription.bedcode,
        prescription.prioritycode,
        prescription.prioritydesc,
        prescription.takedate,
        prescription.ordercreatedate,
        prescription.orderitemcode,
        prescription.orderitemname,
        prescription.orderqty,
        prescription.orderunitcode,
        prescription.orderunitdesc,
        prescription.instructioncode,
        prescription.instructiondesc,
        prescription.dosage,
        prescription.dosageunitcode,
        prescription.dosageunitdesc,
        prescription.frequencycode,
        prescription.frequencydesc,
        prescription.fromlocationname,
        prescription.usercreatecode,
        prescription.usercreatename,
        prescription.orderacceptfromip,
        prescription.computername,
        prescription.itemlotcode,
        prescription.itemlotexpire,
        prescription.doctorcode,
        prescription.doctorname,
        prescription.pharmacyitemcode,
        prescription.pharmacyitemdesc,
        prescription.freetext1,
        prescription.freetext2,
        prescription.freetext3,
        prescription.itemidentify,
        prescription.lastmodified,
        prescription.language,
        prescription.statuscode,
        prescription.ordertype,
        prescription.varymeal,
        prescription.varymealtime,
        prescription.voiddatetime,
        prescription.genorderdatetime,
        prescription.forcash,
        prescription.timecode,
        prescription.timedesc,
        ms_timedetail.timedetailcode,
        ms_timedetail.timedetailTH,
        ms_timedetail.timedetailEN,
        ms_timedetail.varymeal_dosage,
        ms_time.timetype,
        ms_time.timecode AS ms_time_code,
        ms_drug.locationcode,
        ms_drug.shelfzone,
        ms_drug.shelfname,
        ms_drug.shelfname2,
        ms_drug.sendmachine,
        ms_drug.highalert
      FROM
        prescription
        LEFT JOIN packagemaster ON prescription.prescriptionno = packagemaster.prescriptionno AND prescription.seq = packagemaster.seq
        LEFT JOIN ms_time ON LOWER(prescription.timecode) = LOWER(ms_time.timecode)
        LEFT JOIN ms_timedetail ON LOWER(ms_time.timecode) = LOWER(ms_timedetail.timecode)
        LEFT JOIN ms_drug ON prescription.orderitemcode = ms_drug.orderitemcode
`;

module.exports = { sendOrderSelectQuery };
